name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Set up virtual environment and install requirements
        run: |
          python -m venv venv
          call venv\Scripts\activate
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium --with-deps

      - name: Clean previous allure results
        run: |
          if (Test-Path "allure-results") { Remove-Item "allure-results" -Recurse -Force }
          if (Test-Path "allure-report") { Remove-Item "allure-report" -Recurse -Force }
          if (Test-Path "allure-report\history") { 
            New-Item "allure-results" -ItemType Directory -Force 
            Copy-Item "allure-report\history\*" "allure-results\history" -Recurse -Force 
          }

      - name: Run Pytest with Allure
        run: |
          venv\Scripts\python.exe -m pytest test_web\test_runner.py -v --alluredir=allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure CLI
        run: |
          sudo npm install -g allure-commandline --save-dev

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
